import { useState } from 'react';
import { Link } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';
import { errMsg } from '@/lib/format';
import { FeatureShell, LoadState, monthNow, monthRange } from './FeatureUI';
import type { CalendarItem } from '@shared/workspace-features';
export default function OperationsCalendar({staff=false}:{staff?:boolean}){
 const [month,setMonth]=useState(monthNow),[selected,setSelected]=useState(new Date(Date.now()+9*3600000).toISOString().slice(0,10)),[filter,setFilter]=useState('전체'),[form,setForm]=useState(false),[title,setTitle]=useState(''),[kind,setKind]=useState('event'),[end,setEnd]=useState(''),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false);const {toast}=useToast();
 const {from,to}=monthRange(month);const prefix=staff?'/api/staff':'/api/admin';const q=useQuery<CalendarItem[]>({queryKey:[prefix+'/operations-calendar',month],staleTime:0,refetchInterval:60000,queryFn:async()=>(await apiRequest('GET',`${prefix}/operations-calendar?from=${from}&to=${to}`)).json()});
 const rows=(q.data||[]).filter(e=>filter==='전체'||e.kind===filter);const dates=Array.from({length:Number(to.slice(-2))},(_,i)=>month+'-'+String(i+1).padStart(2,'0'));const weekday=new Date(from+'T00:00:00Z').getUTCDay();const events=rows.filter(e=>e.date<=selected&&e.endDate>=selected);
 async function save(){if(busy)return;if(!title.trim()||(end&&end<selected)){toast({variant:'destructive',title:'제목과 일정 날짜를 확인해 주세요.'});return;}setBusy(true);try{await apiRequest('POST',prefix+(staff?'/events':'/staff/events'),{title,kind,startDate:selected,endDate:end||selected,memo});setForm(false);setTitle('');setMemo('');setEnd('');await q.refetch();toast({title:'일정을 등록했어요.'});}catch(e){toast({variant:'destructive',title:errMsg(e)});}finally{setBusy(false);}}
 return <FeatureShell staff={staff} title="매장 운영 캘린더"><div className="f-card"><label>조회 월<input type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(e.target.value+'-01');setForm(false);}}}/></label><div className="f-actions">{['전체','근무','단체주문','행사','방문 세팅','기타·점검'].map(k=><button key={k} aria-pressed={filter===k} onClick={()=>setFilter(k)}>{k}</button>)}</div><LoadState query={q}/><div className="f-calendar">{'일월화수목금토'.split('').map(d=><div className="f-calendar-header" key={d}>{d}</div>)}{Array.from({length:weekday},(_,i)=><div key={'blank'+i}/>)}{dates.map(d=>{const count=rows.filter(e=>e.date<=d&&e.endDate>=d).length;return <button key={d} aria-label={`${d} ${count}건`} aria-pressed={selected===d} onClick={()=>{setSelected(d);setForm(false);}}><span>{Number(d.slice(-2))}</span>{count>0&&<small>{count}건</small>}</button>;})}</div><p className="f-muted mt-3">등록된 근무표·단체주문·행사와 확정된 방문 세팅 일정입니다.</p></div>
 <section className="f-card"><h2>{selected.replaceAll('-','.')}</h2>{!q.isError&&!q.isPending&&!events.length&&<p className="f-muted">등록된 일정이 없습니다.</p>}{events.map(e=><div className="f-row" key={e.id}><p className="f-muted">{e.kind}</p><h3>{e.title}</h3><p className="whitespace-pre-wrap">{e.detail}</p>{e.href&&<Link className="f-button mt-2" href={e.href}>원래 화면에서 보기 · 수정</Link>}</div>)}<div className="f-actions"><button onClick={()=>{setForm(!form);setEnd(selected);}}>일정 추가</button></div>{form&&<fieldset disabled={busy}><p className="f-muted mb-3">이 일정은 직원에게도 공유됩니다.</p><label>제목<input maxLength={60} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>종류<select value={kind} onChange={e=>setKind(e.target.value)}><option value="order">단체주문</option><option value="event">행사</option><option value="etc">기타 · 장비 점검</option></select></label><label>종료일<input type="date" min={selected} value={end} onChange={e=>setEnd(e.target.value)}/></label><label>전달사항<textarea value={memo} maxLength={500} onChange={e=>setMemo(e.target.value)}/></label><button className="f-primary" onClick={save}>{busy?'저장 중…':'일정 저장'}</button></fieldset>}</section>
 </FeatureShell>;
}
export function StaffOperationsCalendar(){return <OperationsCalendar staff/>;}
