import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readOperations, registerAdminOperations } from '../../server/admin-operations';
import { initSupplyWorkflow } from '../../server/supply-workflow';
const db:any=new DatabaseSync(':memory:');
db.exec(`CREATE TABLE staff(id INTEGER,name TEXT,password TEXT,salary INTEGER); INSERT INTO staff VALUES(1,'직원 A','secret',9999);
CREATE TABLE shifts(id INTEGER,staff_id INTEGER,work_date TEXT,start_time TEXT,end_time TEXT,position TEXT);INSERT INTO shifts VALUES(1,1,'2026-09-09','09:00','18:00','바'),(2,1,'2026-09-08','09:00','18:00','바');
CREATE TABLE products(id INTEGER,name TEXT,category TEXT,sort_order INTEGER); INSERT INTO products VALUES(1,'코튼','bean',0),(2,'실크','bean',1),(3,'소모품','other',2);
CREATE TABLE product_categories(key TEXT,is_bean INTEGER);INSERT INTO product_categories VALUES('bean',1),('other',0);
CREATE TABLE supply_orders(id INTEGER,vendor TEXT,body TEXT,order_date TEXT);INSERT INTO supply_orders VALUES(1,'우유','우유 2개','2026-08-01'),(2,'옛 기록','완료 여부 미상','2026-08-01'),(3,'환불','취소','2026-08-01');`);
initSupplyWorkflow(db);
db.exec(`INSERT INTO staff_bean_stock(product_id,grams,tracked) VALUES(1,5500,1),(2,NULL,1),(3,1000,1);
INSERT INTO supply_order_meta(order_id,status) VALUES(1,'partial'),(3,'refunded');`);
const result=readOperations(db,Date.parse('2026-09-08T15:01:00Z'));
assert.equal(result.today,'2026-09-09');assert.equal(result.team.length,1);assert.equal((result.team[0] as any).id,1);
assert.deepEqual(result.stock.map((s:any)=>s.grams),[5500,null]);assert.equal(result.supply.length,1);
assert(!JSON.stringify(result).includes('secret'));assert(!JSON.stringify(result).includes('salary'));
let handlers:any[]=[];const auth=()=>{};registerAdminOperations({get:(path:string,...h:any[])=>{assert.equal(path,'/api/admin/operations');handlers=h;}} as any,db,auth);
assert.equal(handlers[0],auth);assert.equal(handlers.length,2);
const before=db.prepare('SELECT COUNT(*) AS n FROM supply_orders').get();readOperations(db);assert.deepEqual(db.prepare('SELECT COUNT(*) AS n FROM supply_orders').get(),before);
console.log('PASS: KST rollover, explicit staff fields, nullable decimal inventory, legacy/completed supply excluded, admin middleware and read-only query');
