import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {initScheduleApproval,decideSchedule,applyLeaveDecision,assertNoLeave} from '../../server/schedule-approval.ts';
const native=new DatabaseSync(':memory:');
const db:any={prepare:(s:string)=>native.prepare(s),exec:(s:string)=>native.exec(s),transaction:(f:any)=>(...args:any[])=>{native.exec('BEGIN');try{const result=f(...args);native.exec('COMMIT');return result;}catch(e){native.exec('ROLLBACK');throw e;}}};
db.exec(`CREATE TABLE shifts(id INTEGER PRIMARY KEY,staff_id INTEGER,work_date TEXT,position TEXT,start_time TEXT,end_time TEXT,memo TEXT);CREATE TABLE attendance(id INTEGER PRIMARY KEY,staff_id INTEGER,work_date TEXT,clock_in_at INTEGER);CREATE TABLE leave_requests(id INTEGER PRIMARY KEY,staff_id INTEGER,start_date TEXT,end_date TEXT,half_day INTEGER,status TEXT,decided_by_name TEXT,decided_at INTEGER,admin_memo TEXT);`);
initScheduleApproval(db);
const date='2099-01-05';
function shift(id:number,staff:number,position='Open'){db.prepare('INSERT INTO shifts VALUES(?,?,?,?,?,?,?)').run(id,staff,date,position,'07:30','16:30','');}
function request(id:number,shiftId:number,after:any={workDate:date,position:'Baker',startTime:'08:00',endTime:'17:00'}){const before:any=db.prepare('SELECT * FROM shifts WHERE id=?').get(shiftId);db.prepare('INSERT INTO schedule_change_requests(id,staff_id,staff_name,shift_id,before_json,after_json,reason,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,before.staff_id,'테스트',shiftId,JSON.stringify(before),JSON.stringify(after),'변경',1);}
shift(1,1);request(1,1);assert.equal(db.prepare('SELECT position FROM shifts WHERE id=1').get().position,'Open');decideSchedule(db,1,'approved','owner:1','');assert.equal(db.prepare('SELECT position FROM shifts WHERE id=1').get().position,'Baker');assert.throws(()=>decideSchedule(db,1,'approved','owner:1',''));
shift(2,2);request(2,2);decideSchedule(db,2,'rejected','owner:1','반려');assert.equal(db.prepare('SELECT position FROM shifts WHERE id=2').get().position,'Open');
request(3,2);db.prepare('UPDATE shifts SET memo=? WHERE id=2').run('다른 수정');assert.throws(()=>decideSchedule(db,3,'approved','owner:1',''),/근무표가 변경/);assert.equal(db.prepare('SELECT status FROM schedule_change_requests WHERE id=3').get().status,'pending');
shift(4,4,'Part');request(4,4);assert.throws(()=>decideSchedule(db,4,'approved','owner:1',''),/다른 직원/);assert.equal(db.prepare('SELECT position FROM shifts WHERE id=4').get().position,'Part');
db.prepare('INSERT INTO leave_requests VALUES(1,1,?,?,0,?,?,?,?)').run(date,date,'pending','',null,'');applyLeaveDecision(db,1,'approved','소유자','');assert.equal(db.prepare('SELECT id FROM shifts WHERE id=1').get(),undefined);assert.throws(()=>assertNoLeave(db,1,date));assert.throws(()=>applyLeaveDecision(db,1,'rejected','소유자',''));
db.prepare('INSERT INTO leave_requests VALUES(2,2,?,?,1,?,?,?,?)').run(date,date,'pending','',null,'');assert.throws(()=>applyLeaveDecision(db,2,'approved','소유자',''),/반차/);assert.equal(db.prepare('SELECT status FROM leave_requests WHERE id=2').get().status,'pending');applyLeaveDecision(db,2,'approved','소유자','',{startTime:'12:00',endTime:'16:30'});assert.equal(db.prepare('SELECT start_time FROM shifts WHERE id=2').get().start_time,'12:00');
db.prepare('INSERT INTO leave_requests VALUES(3,4,?,?,0,?,?,?,?)').run(date,date,'pending','',null,'');db.prepare('INSERT INTO attendance VALUES(1,4,?,1)').run(date);assert.throws(()=>applyLeaveDecision(db,3,'approved','소유자',''),/출근/);assert.ok(db.prepare('SELECT id FROM shifts WHERE id=4').get());
console.log('Passed: pending isolation, approve, reject, repeated decision, stale schedule, slot conflict, full leave, reassign protection, half-day rollback and hours, attendance protection.');
