import { useTodayTarget, useTodayScroll } from '@/lib/today-target';
import { needsDepositReview } from '@shared/today-tasks';
import BankOnline from './BankOnline';
import { AdminFold } from "@/components/AdminFold";
import BankTransactions, { bankStateLabels as labels, type BankRow as Row } from "./BankTransactions";
import BankPosting, { TestLedgerSummary } from "./BankPosting";
import { useEffect, useState } from 'react';
import BankBulkPayments from './BankBulkPayments';
import { BANK_BULK_LIMIT } from '@shared/bank-bulk-payments';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AdminLayout } from '@/components/AdminLayout';
import { apiRequest } from '@/lib/queryClient';
import { useAuth } from '@/lib/auth';
import { Link } from 'wouter';
const money=(v:number)=>v.toLocaleString('ko-KR');
export default function BankReview(){
 const [environment,setEnvironment]=useState<'test'|'production'>('production');
 return <BankReviewPage key={environment} environment={environment} setEnvironment={setEnvironment}/>;
}
function BankReviewPage({environment,setEnvironment}:{environment:'test'|'production';setEnvironment:(value:'test'|'production')=>void}){
 const todayTarget=useTodayTarget('deposits');
 const [bulkIds,setBulkIds]=useState<number[]|null>(null),[focusRow,setFocusRow]=useState<number|null>(null);
 useEffect(()=>{if(focusRow!==null&&!bulkIds){const row=document.getElementById(`bank-task-${focusRow}`);row?.scrollIntoView({block:'center'});row?.focus();setFocusRow(null);}},[focusRow,bulkIds]);
 const live=environment==='production',base=live?'/api/admin/bank-live':'/api/admin/bank-review',ledger=live?'/api/admin/bank-live-ledger':'/api/admin/bank-test-ledger';
 const [key,setKey]=useState(''),[corp,setCorp]=useState(''),[id,setId]=useState('');

 const cache=useQueryClient();
 const {user}=useAuth();const owner=(user as any)?.adminRole==='owner';
 const q=useQuery<{environment:string;configured:boolean;rows:Row[]}>({queryKey:[base],enabled:owner,staleTime:0});
 const [from,setFrom]=useState(new Date().toISOString().slice(0,7)+'-01'),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const [filter,setFilter]=useState(todayTarget?'needs-deposit':'all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Row|null>(null),[state,setState]=useState('pending'),[target,setTarget]=useState(''),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const candidates=useQuery<{type:string;customers:{id:number;name:string}[];candidates:{id:number;date:string;label:string;amount:number}[]}>({queryKey:[`${base}/${selected?.id}/candidates`],enabled:owner&&!!selected,staleTime:0});
 const quickCustomers=useQuery<{id:number;businessName:string;role:string}[]>({queryKey:['/api/admin/customers'],enabled:owner});
 const quickCategories=useQuery<{name:string;sector:string;costType:string;active:boolean}[]>({queryKey:['/api/admin/fixed-cost-items'],enabled:owner});
 const refresh=async()=>{const updated=await q.refetch();if(selected){const fresh=updated.data?.rows.find(r=>r.id===selected.id);if(fresh){setSelected(fresh);setState(fresh.state);setTarget(fresh.targetId?String(fresh.targetId):'');setMemo(fresh.memo);}}await cache.invalidateQueries(live?{}:{queryKey:[ledger]});};
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();await q.refetch();}catch(e:any){setMessage(e.message||'처리하지 못했습니다.');}finally{setBusy(false);}};
 const rows=(q.data?.rows||[]).filter(r=>(filter==='all'||filter==='needs-deposit'&&needsDepositReview(r)||['settlement','online','delivery','card'].includes(filter)&&r.state===filter||filter==='deposit'&&r.deposit>0||filter==='withdraw'&&r.withdraw>0||filter==='pending'&&r.state==='pending'&&!r.posted)&&(!search||`${r.remark} ${r.memo}`.includes(search)));
 const bulkCandidates=rows.filter(r=>r.state==='pending'&&!r.posted&&r.deposit>0&&r.withdraw===0&&r.customerSuggestion);
 useTodayScroll(`bank-task-${todayTarget?.id}`,!!todayTarget?.id&&!!q.data);
 return <AdminLayout><div className="erp-page bank-review-page"><div className="erp-page-heading"><div><small>FINANCE · {live?'운영':'테스트'}</small><h1>통장 내역</h1></div><details className="text-sm"><summary>{live?'운영 · 환경 설정':'테스트 모드 · 환경 설정'}</summary><label className="block py-2">조회 환경 <select aria-label="조회 환경" disabled={!!bulkIds} value={environment} onChange={e=>setEnvironment(e.target.value as 'test'|'production')}><option value="test">테스트</option><option value="production">운영</option></select></label></details></div>{!owner?<p>대표 계정에서 확인할 수 있어요.</p>:<>
 <div className="bank-sync-controls flex flex-wrap gap-3 items-center my-5"><label>시작일 <input aria-label="시작일" type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>종료일 <input aria-label="종료일" type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><button className="border rounded px-4 py-2" disabled={busy||!q.data?.configured} onClick={()=>action(async()=>{const res=await apiRequest('POST',base+'/sync',{from,to});const result=await res.json();setMessage(`${result.received}건 확인 · 새 내역 ${result.added}건 추가`);})}>{busy?'처리 중…':'입출금 가져오기'}</button></div>
{q.data&&!q.data.configured&&<p role="status">바로빌 연결 정보를 저장하면 직접 조회할 수 있습니다.</p>}{message&&<p role="status" className="my-3">{message}</p>}{q.isError&&<p role="alert">내역을 불러오지 못했습니다. <button onClick={()=>q.refetch()}>다시 시도</button></p>}
 <AdminFold id={`bank-${environment}-details`} title="안내 · 연결 설정 · 반영 현황"> <p>{live?'운영 계좌를 조회합니다. 내역을 가져오기만 하면 장부 금액은 바뀌지 않습니다. 검토 후 운영 장부에 반영한 건만 비용·수금에 포함됩니다.':'테스트 장부에서 비용 등록과 수금 반영을 확인합니다. 운영 재무제표와 거래처 잔액은 변경되지 않습니다.'}</p>
 <details className="border rounded p-4 my-4"><summary>바로빌 {live?'운영':'테스트'} 연결 설정 · {q.data?.configured?'저장됨':'미설정'}</summary><p className="text-sm my-2">선택한 환경의 인증키와 바로빌 회원 정보를 입력해 주세요. 인증키는 암호화해 저장합니다.</p><div className="flex flex-wrap gap-3"><input aria-label="바로빌 인증키" type="password" autoComplete="new-password" placeholder="인증키" value={key} onChange={e=>setKey(e.target.value)}/><input aria-label="사업자번호" placeholder="사업자번호 10자리" value={corp} onChange={e=>setCorp(e.target.value.replace(/[^0-9]/g,''))}/><input aria-label="바로빌 아이디" placeholder="바로빌 회원 아이디" value={id} onChange={e=>setId(e.target.value)}/><button disabled={busy||!key||corp.length!==10||!id} onClick={()=>action(async()=>{await apiRequest('POST',`/api/admin/bank-connection/${environment}`,{key,corp,id});setKey('');setMessage('연결 정보를 저장했습니다. 입출금 가져오기로 조회를 확인해 주세요.');})}>연결 정보 저장</button></div></details>
 {!live&&<label className="block my-3">테스트 내역 파일 가져오기 <input type="file" accept=".json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;action(async()=>{if(file.size>2000000)throw new Error('2MB 이하 파일을 선택해 주세요.');const payload=JSON.parse(await file.text());const res=await apiRequest('POST',base+'/import',payload);const result=await res.json();setMessage(`${result.received}건 확인 · 새 내역 ${result.added}건 추가`);});e.target.value='';}} /></label>}<p className="text-sm my-3">매장 정산 입금은 매출·미수금을 바꾸지 않고 분류만 저장합니다. 이미 비용으로 기록한 카드 결제대금도 다시 비용에 추가하지 않습니다. 수금·비용 반영은 선택한 거래처·항목으로 표시 금액 전체를 반영합니다.</p><TestLedgerSummary live={live}/></AdminFold>
 <div className="bank-list-filters flex flex-wrap gap-3 my-4"><select aria-label="내역 구분" disabled={!!bulkIds} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">입출금 전체</option><option value="needs-deposit">확인할 입금</option><option value="deposit">입금</option><option value="withdraw">출금</option><option value="pending">미확인</option><option value="settlement">매장 정산 입금</option><option value="online">온라인 정산 입금</option><option value="delivery">배달 정산 입금</option><option value="card">카드대금 출금</option></select><input aria-label="적요 검색" disabled={!!bulkIds} placeholder="적요·메모 검색" value={search} onChange={e=>setSearch(e.target.value)} /><span>{rows.length}건 · 입금 {money(rows.reduce((s,r)=>s+r.deposit,0))}원 · 출금 {money(rows.reduce((s,r)=>s+r.withdraw,0))}원</span></div>
 {!bulkIds&&bulkCandidates.length>0&&<div className="bank-bulk-entry"><button className="border rounded px-4 py-2" disabled={q.isError} onClick={()=>{setSelected(null);setBulkIds(bulkCandidates.slice(0,BANK_BULK_LIMIT).map(r=>r.id));}}>추천 입금 모아 반영 · {Math.min(bulkCandidates.length,BANK_BULK_LIMIT)}건</button><span>현재 목록 기준{bulkCandidates.length>BANK_BULK_LIMIT?` · 한 번에 최대 ${BANK_BULK_LIMIT}건`:''}</span></div>}
 {bulkIds&&<BankBulkPayments ids={bulkIds} live={live} onChange={refresh} onClose={()=>{setBulkIds(null);void refresh();}} onReview={id=>{const row=q.data?.rows.find(r=>r.id===id);setBulkIds(null);if(row){setSelected(row);setState(row.state);setTarget(row.targetId?String(row.targetId):'');setMemo(row.memo);setFocusRow(id);}}}/>}
 {!bulkIds&&<>{(quickCustomers.isError||quickCategories.isError)&&<p role="alert">바로 처리 항목을 불러오지 못했습니다. <button onClick={()=>{quickCustomers.refetch();quickCategories.refetch();}}>다시 시도</button></p>}<BankTransactions rows={rows} live={live} selectedId={selected?.id} highlightedId={todayTarget?.id}
 customers={(quickCustomers.data||[]).filter(c=>c.role==='customer').map(c=>({id:c.id,name:c.businessName}))}
 categories={(quickCategories.data||[]).filter(c=>c.active&&['cogs','sga'].includes(c.costType))}
 onChange={refresh} onDetails={r=>{setMessage('');setSelected(selected?.id===r.id?null:r);setState(r.state);setTarget(r.targetId?String(r.targetId):'');setMemo(r.memo);}}>
 {selected&&<div><button className="float-right border rounded px-3 py-1" onClick={()=>setSelected(null)}>상세 닫기</button><h2 className="font-semibold">{selected.remark} · {money(selected.deposit||selected.withdraw)}원</h2><p className="text-sm text-gray-600 my-2">연결 후보는 같은 금액, 거래일 전후 7일의 기존 기록입니다. 실제 사용 내역을 확인해 주세요.</p>{message&&<p role="alert">{message}</p>}{selected.state==='online'&&<BankOnline id={selected.id} live={live} deposit={selected.deposit} onChange={refresh}/>}<BankPosting live={live} key={`${selected.id}-${selected.state}-${selected.targetId}`} row={selected} customers={candidates.data?.customers||[]} onChange={async()=>{const updated=await q.refetch();const fresh=updated.data?.rows.find(r=>r.id===selected.id);if(fresh){setSelected(fresh);setState(fresh.state);setTarget(fresh.targetId?String(fresh.targetId):'');setMemo(fresh.memo);}await cache.invalidateQueries(live?{}:{queryKey:[ledger]});}}/><details className="border-t mt-4 pt-4"><summary>기타 처리 · 기존 기록 연결 / 정산 입금 / 분류</summary>{selected.posted?<p className="font-semibold">{live?'운영 장부 반영 완료':'테스트 반영 완료'}</p>:<select aria-label="분류" value={state} onChange={e=>{setState(e.target.value);setTarget('');}}>{Object.entries(labels).filter(([k])=>k!=='expense'||selected.withdraw>0).filter(([k])=>!['payment','customer','settlement','online','delivery'].includes(k)||selected.deposit>0).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>}
 {['expense','payment'].includes(state)&&<div className="my-3">{candidates.isLoading?'후보 확인 중…':candidates.isError?'후보를 불러오지 못했습니다.':<><select aria-label="연결할 기록" value={target} onChange={e=>setTarget(e.target.value)}><option value="">기존 기록 선택</option>{candidates.data?.candidates.map(c=><option key={c.id} value={c.id}>{c.date} · {c.label} · {money(c.amount)}원</option>)}</select>{!candidates.data?.candidates.length&&<p>일치하는 후보가 없습니다. 부분 결제·합산 결제는 미확인으로 남겨 주세요.</p>}</>}</div>}
 {state==='customer'&&<select aria-label="입금 거래처" value={target} onChange={e=>setTarget(e.target.value)}><option value="">거래처 선택</option>{candidates.data?.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}
 <textarea className="block border w-full my-3 p-2" aria-label="검토 메모" placeholder="검토 메모" maxLength={500} value={memo} onChange={e=>setMemo(e.target.value)} /><div className="flex gap-4"><button disabled={busy||!!selected.posted||(['expense','payment','customer'].includes(state)&&!target)} onClick={()=>action(async()=>{await apiRequest('PATCH',`${base}/${selected.id}`,{state,targetId:['expense','payment','customer'].includes(state)?Number(target):null,memo});setSelected({...selected,state,targetId:['expense','payment','customer'].includes(state)?Number(target):null,memo});setMessage('분류를 저장했습니다. 장부 금액은 변경하지 않았습니다.');})}>검토 저장</button><button disabled={busy} onClick={()=>setSelected(null)}>닫기</button><Link href="/admin/expenses">기존 비용 장부 열기</Link></div></details></div>}</BankTransactions>{q.isLoading?<p>불러오는 중…</p>:!rows.length&&!q.isError&&<p className="py-8">표시할 내역이 없습니다.</p>}</>}

 </>}</div></AdminLayout>;
}
