import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import BankPosting, { TestLedgerSummary } from "./BankPosting";
import { useState, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AdminLayout } from '@/components/AdminLayout';
import { apiRequest } from '@/lib/queryClient';
import { useAuth } from '@/lib/auth';
import { Link } from 'wouter';
const labels:Record<string,string>={pending:'미확인',customer:'거래처 연결 후보',expense:'기존 비용 연결',payment:'기존 수금 연결',transfer:'계좌 간 이동',card:'카드대금',loan:'대출 관련',other:'기타'};
const money=(v:number)=>v.toLocaleString('ko-KR');
type Row={id:number;at:string;deposit:number;withdraw:number;remark:string;state:string;targetId:number|null;memo:string;account:string;posted:number};
export default function BankReview(){
 const reviewButton=useRef<HTMLButtonElement|null>(null);
 const cache=useQueryClient();
 const {user}=useAuth();const owner=(user as any)?.adminRole==='owner';
 const q=useQuery<{environment:string;configured:boolean;rows:Row[]}>({queryKey:['/api/admin/bank-review'],enabled:owner,staleTime:0});
 const [from,setFrom]=useState(new Date().toISOString().slice(0,7)+'-01'),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Row|null>(null),[state,setState]=useState('pending'),[target,setTarget]=useState(''),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const candidates=useQuery<{type:string;customers:{id:number;name:string}[];candidates:{id:number;date:string;label:string;amount:number}[]}>({queryKey:[`/api/admin/bank-review/${selected?.id}/candidates`],enabled:owner&&!!selected,staleTime:0});
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();await q.refetch();}catch(e:any){setMessage(e.message||'처리하지 못했습니다.');}finally{setBusy(false);}};
 const rows=(q.data?.rows||[]).filter(r=>(filter==='all'||filter==='deposit'&&r.deposit>0||filter==='withdraw'&&r.withdraw>0||filter==='pending'&&r.state==='pending')&&(!search||`${r.remark} ${r.memo}`.includes(search)));
 return <AdminLayout><div className="erp-page"><div className="erp-page-heading"><div><small>FINANCE · TEST</small><h1>통장 내역</h1></div></div>{!owner?<p>대표 계정에서 확인할 수 있어요.</p>:<>
 <p>테스트 장부에서 비용 등록과 수금 반영을 확인합니다. 운영 재무제표와 거래처 잔액은 변경되지 않습니다.</p>
 <div className="flex flex-wrap gap-3 items-center my-5"><label>시작일 <input aria-label="시작일" type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>종료일 <input aria-label="종료일" type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><button className="border rounded px-4 py-2" disabled={busy||!q.data?.configured} onClick={()=>action(async()=>{const res=await apiRequest('POST','/api/admin/bank-review/sync',{from,to});const result=await res.json();setMessage(`${result.received}건 확인 · 새 내역 ${result.added}건 추가`);})}>{busy?'처리 중…':'입출금 가져오기'}</button></div>
 <label className="block my-3">테스트 내역 파일 가져오기 <input type="file" accept=".json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;action(async()=>{if(file.size>2000000)throw new Error('2MB 이하 파일을 선택해 주세요.');const payload=JSON.parse(await file.text());const res=await apiRequest('POST','/api/admin/bank-review/import',payload);const result=await res.json();setMessage(`${result.received}건 확인 · 새 내역 ${result.added}건 추가`);});e.target.value='';}} /></label>{q.data&&!q.data.configured&&<p role="status">자동 조회 연결 전에는 테스트 내역 파일로 이용할 수 있습니다.</p>}{message&&<p role="status" className="my-3">{message}</p>}{q.isError&&<p role="alert">내역을 불러오지 못했습니다. <button onClick={()=>q.refetch()}>다시 시도</button></p>}
 <TestLedgerSummary/>
 <div className="flex flex-wrap gap-3 my-4"><select aria-label="내역 구분" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">입출금 전체</option><option value="deposit">입금</option><option value="withdraw">출금</option><option value="pending">미확인</option></select><input aria-label="적요 검색" placeholder="적요·메모 검색" value={search} onChange={e=>setSearch(e.target.value)} /><span>{rows.length}건 · 입금 {money(rows.reduce((s,r)=>s+r.deposit,0))}원 · 출금 {money(rows.reduce((s,r)=>s+r.withdraw,0))}원</span></div>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['일시 / 계좌','적요','입금','출금','검토 상태',''].map((s,i)=><th className="text-left border-b p-3" key={i}>{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="p-3 border-b whitespace-nowrap">{r.at.slice(0,4)}-{r.at.slice(4,6)}-{r.at.slice(6,8)} {r.at.slice(8,10)}:{r.at.slice(10,12)}<small className="block text-gray-500">{r.account}</small></td><td className="p-3 border-b">{r.remark}</td><td className="p-3 border-b tabular-nums">{r.deposit?money(r.deposit):'—'}</td><td className="p-3 border-b tabular-nums">{r.withdraw?money(r.withdraw):'—'}</td><td className="p-3 border-b whitespace-nowrap">{r.posted?'테스트 반영 완료':labels[r.state]}</td><td className="p-3 border-b"><button disabled={busy} onClick={e=>{reviewButton.current=e.currentTarget;setMessage('');setSelected(r);setState(r.state);setTarget(r.targetId?String(r.targetId):'');setMemo(r.memo);}}>검토</button></td></tr>)}</tbody></table></div>{q.isLoading?<p>불러오는 중…</p>:!rows.length&&!q.isError&&<p className="py-8">표시할 내역이 없습니다.</p>}
 {selected&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setSelected(null);}}><DialogContent key={selected.id} className="w-[calc(100%-2rem)] max-w-2xl max-h-[85dvh] overflow-y-auto" onCloseAutoFocus={e=>{e.preventDefault();reviewButton.current?.focus();}}><DialogTitle className="pr-8 leading-snug">{selected.remark} · {money(selected.deposit||selected.withdraw)}원</DialogTitle><DialogDescription>연결 후보는 같은 금액, 거래일 전후 7일의 기존 기록입니다. 실제 사용 내역을 확인해 주세요.</DialogDescription>{message&&<p role="alert">{message}</p>}<select aria-label="분류" value={state} onChange={e=>{setState(e.target.value);setTarget('');}}>{Object.entries(labels).filter(([k])=>k!=='expense'||selected.withdraw>0).filter(([k])=>!['payment','customer'].includes(k)||selected.deposit>0).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
 {['expense','payment'].includes(state)&&<div className="my-3">{candidates.isLoading?'후보 확인 중…':candidates.isError?'후보를 불러오지 못했습니다.':<><select aria-label="연결할 기록" value={target} onChange={e=>setTarget(e.target.value)}><option value="">기존 기록 선택</option>{candidates.data?.candidates.map(c=><option key={c.id} value={c.id}>{c.date} · {c.label} · {money(c.amount)}원</option>)}</select>{!candidates.data?.candidates.length&&<p>일치하는 후보가 없습니다. 부분 결제·합산 결제는 미확인으로 남겨 주세요.</p>}</>}</div>}
 {state==='customer'&&<select aria-label="입금 거래처" value={target} onChange={e=>setTarget(e.target.value)}><option value="">거래처 선택</option>{candidates.data?.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}
 <textarea className="block border w-full my-3 p-2" aria-label="검토 메모" placeholder="검토 메모" maxLength={500} value={memo} onChange={e=>setMemo(e.target.value)} /><div className="flex gap-4"><button disabled={busy||!!selected.posted||(['expense','payment','customer'].includes(state)&&!target)} onClick={()=>action(async()=>{await apiRequest('PATCH',`/api/admin/bank-review/${selected.id}`,{state,targetId:['expense','payment','customer'].includes(state)?Number(target):null,memo});setSelected(null);setMessage('검토 내용을 저장했습니다. 장부 금액은 변경하지 않았습니다.');})}>검토 저장</button><button disabled={busy} onClick={()=>setSelected(null)}>닫기</button><Link href="/admin/expenses">기존 비용 장부 열기</Link></div><BankPosting key={selected.id} row={selected} customers={candidates.data?.customers||[]} onChange={async()=>{const updated=await q.refetch();const fresh=updated.data?.rows.find(r=>r.id===selected.id);if(fresh)setSelected(fresh);await cache.invalidateQueries({queryKey:['/api/admin/bank-test-ledger']});}}/></DialogContent></Dialog>}
 </>}</div></AdminLayout>;
}
