import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {Link} from 'wouter';
export default function BankOnline({id,live,deposit,onChange}:{id:number;live:boolean;deposit:number;onChange:()=>Promise<unknown>}){
 const url=`${live?'/api/admin/bank-live':'/api/admin/bank-review'}/${id}/online`;
 const q=useQuery<{saved:null|{channel:string;fees:number;sales:string};sales:{id:number;date:string;amount:number;memo:string}[]}>({queryKey:[url]});
 const [channel,setChannel]=useState('스마트스토어'),[fees,setFees]=useState('0'),[ids,setIds]=useState<number[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const total=(q.data?.sales||[]).filter(s=>ids.includes(s.id)).reduce((sum,s)=>sum+s.amount,0);
 async function run(method:string){if(busy)return;setBusy(true);setError('');try{await apiRequest(method,url,method==='POST'?{channel,fees:Number(fees),saleIds:ids}:undefined);await q.refetch();await onChange();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="border rounded p-4 my-4"><h3 className="font-semibold">온라인 매출 연결 {live?'':'· 테스트'}</h3><p className="text-sm my-2">이미 입력한 온라인 매출의 정산 입금을 연결합니다. 매출·수수료 비용을 새로 등록하지 않습니다.</p>{q.isLoading?<p>불러오는 중…</p>:q.isError?<button onClick={()=>q.refetch()}>불러오기 실패 · 다시 시도</button>:q.data?.saved?<><p role="status">연결 완료 · {q.data.saved.channel} · 입금 {deposit.toLocaleString()}원 · 수수료 {q.data.saved.fees.toLocaleString()}원</p><p>연결 매출: {q.data.sales.filter(s=>JSON.parse(q.data!.saved!.sales).includes(s.id)).map(s=>`${s.date} ${s.amount.toLocaleString()}원`).join(', ')}</p><button disabled={busy} onClick={()=>run('DELETE')}>매출 연결 해제</button></>:<><div className="flex gap-3 flex-wrap my-3"><label>판매 채널 <input aria-label="판매 채널" maxLength={80} value={channel} onChange={e=>setChannel(e.target.value)}/></label><label>정산서 수수료(원) <input aria-label="정산서 수수료" type="number" min="0" step="1" value={fees} onChange={e=>setFees(e.target.value)}/></label></div><div className="max-h-56 overflow-y-auto">{q.data?.sales.map(s=><label key={s.id} className="block py-1"><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(x=>x!==s.id))}/> {s.date} · {s.amount.toLocaleString()}원 · {s.memo}</label>)}</div>{!q.data?.sales.length&&<p>등록된 온라인 매출이 없습니다. 기존 매출 입력 화면에서 먼저 등록해 주세요.</p>}<p className="my-2">선택 매출 {total.toLocaleString()}원 − 수수료 {Number(fees||0).toLocaleString()}원 / 통장 입금 {deposit.toLocaleString()}원</p><p className="text-sm">합산 정산은 여러 매출을 선택하세요. 부분 정산·환불 등으로 금액이 다르면 연결을 보류하세요.</p><button className="border rounded p-2 my-2" disabled={busy||!channel.trim()||!ids.length||fees===''||Number(fees)<0||total-Number(fees)!==deposit} onClick={()=>run('POST')}>{busy?'저장 중…':'정산 입금 연결'}</button></>}{error&&<p role="alert">{error}</p>}</section>;
}
