import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
const money=(v:number)=>v.toLocaleString('ko-KR');
export const orderTaxLabels:Record<string,string>={unissued:'미발행',draft:'발행 준비',issued:'발행 완료',sending:'발행 중',unknown:'확인 필요',rejected:'발행 실패',changed:'주문 변경 · 확인 필요',external:'기존 발행 기록'};
export default function OrderInvoiceQueue({env,supplier,PartyFields,onDocument}:{env:string;supplier:any;PartyFields:any;onDocument:(r:any)=>void}){
 const cache=useQueryClient();
 const base=`/api/admin/tax-invoices/${env}`,q=useQuery<any>({queryKey:[base+'/orders'],staleTime:0});
 const orderId=new URLSearchParams(window.location.search).get('order');
 const [filter,setFilter]=useState(orderId?'all':'unissued'),[search,setSearch]=useState(orderId||''),[ids,setIds]=useState<number[]>([]),[mode,setMode]=useState('each'),[groups,setGroups]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]);
 const [date,setDate]=useState(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'})),[purpose,setPurpose]=useState('2'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false),[approval,setApproval]=useState('');
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();await q.refetch();await cache.invalidateQueries({queryKey:[base]});}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
 const post=async(path:string,p:any)=>(await apiRequest('POST',base+path,p)).json();
 const rows=(q.data?.rows||[]).filter((r:any)=>(filter==='all'||r.state===filter)&&(!search||String(r.id)===search||`${r.orderNo} ${r.name}`.includes(search)));
 const selected=(q.data?.rows||[]).filter((r:any)=>ids.includes(r.id)&&r.state==='unissued');
 const prepare=()=>{const g:any[]=[];for(const r of selected){let found=mode==='customer'?g.find(v=>v.customerId===r.customerId):null;if(!found){found={customerId:r.customerId,buyer:{...r.buyer},orders:[],ids:[]};g.push(found);}found.orders.push(r);found.ids.push(r.id);}setGroups(g);setDocs([]);setConfirmed(false);};
 return <section className="border rounded p-4 my-5"><h2 className="font-semibold">주문별 세금계산서</h2><p className="text-sm my-2">처리 완료된 유상 주문을 기준으로 발행합니다. 건별 또는 같은 거래처 합산을 선택하세요. 외부에서 발행한 건은 기존 발행 기록으로 연결해 주세요.</p>
 {message&&<p role="status" className="my-3">{message}</p>}{q.isError&&<p>주문을 불러오지 못했습니다. <button onClick={()=>q.refetch()}>다시 시도</button></p>}
 <div className="flex gap-3 flex-wrap my-3"><select aria-label="주문 발행 상태" disabled={busy} value={filter} onChange={e=>{setFilter(e.target.value);setIds([]);}}><option value="all">전체 상태</option>{Object.entries(orderTaxLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><input aria-label="발행 주문 검색" className="border rounded p-2" placeholder="거래처·주문번호" value={search} onChange={e=>{setSearch(e.target.value);setIds([]);}}/><button disabled={busy} onClick={()=>q.refetch()}>새로고침</button></div>
 <div className="overflow-auto max-h-[440px]"><table className="w-full text-sm"><thead><tr>{['선택','주문','거래처','합계','발행 상태',''].map((s,i)=><th className="text-left p-2 border-b" key={i}>{s}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td className="p-2 border-b"><input aria-label={`${r.orderNo} 선택`} type="checkbox" disabled={busy||r.state!=='unissued'} checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/></td><td className="p-2 border-b">{r.orderNo}<small className="block">{r.date}</small></td><td className="p-2 border-b">{r.name}</td><td className="p-2 border-b">{money(r.total)}원</td><td className="p-2 border-b">{orderTaxLabels[r.state]||r.state}</td><td className="p-2 border-b">{r.draftId&&<button disabled={busy} onClick={()=>act(async()=>onDocument(await (await apiRequest('GET',base+'/drafts/'+r.draftId)).json()))}>문서 확인</button>}</td></tr>)}</tbody></table></div>
 <div className="flex flex-wrap gap-3 my-3"><button disabled={busy} onClick={()=>setIds(rows.filter((r:any)=>r.state==='unissued').slice(0,100).map((r:any)=>r.id))}>미발행 모두 선택 (최대 100건)</button><span>{selected.length}건 · {money(selected.reduce((s:number,r:any)=>s+r.total,0))}원</span><select disabled={busy} value={mode} onChange={e=>setMode(e.target.value)}><option value="each">주문별 각각 발행</option><option value="customer">거래처별 합산 발행</option></select><button className="border rounded p-2" disabled={busy||!selected.length||selected.length>100} onClick={prepare}>선택 주문 발행 준비</button></div>
 <details className="my-3"><summary>이미 발행한 주문 연결</summary><p className="text-sm my-2">같은 세금계산서에 전액 포함된 주문만 선택하고 국세청 승인번호를 입력하세요. 직접 확인한 기록으로 저장하며, 외부 발행 여부를 자동 조회하지 않습니다.</p><input className="border p-2" aria-label="기존 발행 승인번호" placeholder="국세청 승인번호 24자리" value={approval} onChange={e=>setApproval(e.target.value.replace(/\D/g,''))}/><button disabled={busy||!selected.length||approval.length!==24} onClick={()=>{if(window.confirm('선택한 주문 전액이 이 승인번호로 이미 발행된 것을 확인했나요?'))act(async()=>{await post('/orders/external',{ids:selected.map((r:any)=>r.id),approval,confirmed:true});setIds([]);setApproval('');setMessage('기존 발행 기록으로 연결했습니다.');});}}>확인한 기존 발행 기록 저장</button></details>
 {groups.length>0&&docs.length===0&&<div className="border-t pt-4"><h3 className="font-semibold">발행 준비 · {groups.length}장</h3><label>작성일 <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="2">청구</option><option value="1">영수</option></select>
 <details className="my-3"><summary>공급자 확인: {supplier.name||'정보 입력 필요'} · {supplier.corpNum}</summary><p>{supplier.ceo} · {supplier.address} · {supplier.email}</p></details>
 {groups.map((g,i)=><div key={i} className="border rounded p-3 my-3"><h4>{g.orders[0].name} · {g.orders.length}건 · {money(g.orders.reduce((s:number,r:any)=>s+r.total,0))}원</h4><p className="text-sm">{g.orders.map((r:any)=>r.orderNo).join(', ')}</p>{g.orders.some((r:any)=>r.ecountSent)&&<p className="text-sm my-2">이카운트 판매전표 전송 이력이 있습니다. 세금계산서도 이미 발행했는지 확인해 주세요.</p>}<PartyFields prefix={`주문 ${i+1} 공급받는자`} value={g.buyer} onChange={(buyer:any)=>setGroups(groups.map((v,n)=>n===i?{...v,buyer}:v))}/><details><summary>주문 품목·할인 확인</summary>{g.orders.map((r:any)=><div key={r.id}><p>{r.orderNo}</p>{r.items.map((l:any,n:number)=><p key={n}>{l.name} · {l.qty} × {money(l.unitPrice)}원 · {money(l.amount)}원</p>)}{r.discount>0&&<p>할인 −{money(r.discount)}원</p>}<p>공급가액 {money(r.amount)}원 · 세액 {money(r.tax)}원</p></div>)}</details></div>)}
 <button className="border rounded p-2" disabled={busy} onClick={()=>act(async()=>{const r=await post('/order-drafts',{supplier,date,purpose,groups:groups.map(g=>({ids:g.ids,buyer:g.buyer}))});setDocs(r.rows);setConfirmed(false);setIds([]);})}>발행 문서 저장·최종 확인</button><button className="ml-3" onClick={()=>setGroups([])}>준비 닫기</button></div>}
 {docs.length>0&&<div className="border-t pt-4"><h3 className="font-semibold">{env==='production'?'실제 발행':'테스트 발행'} 최종 확인 · {docs.length}장</h3>{docs.map(d=><div key={d.id} className="border rounded p-3 my-2"><strong>{d.payload.buyer.name} · {money(d.payload.amount+d.payload.tax)}원</strong><p>{d.payload.date} · {d.payload.buyer.corpNum} · {d.payload.buyer.email} · {orderTaxLabels[d.state]||d.state}</p>{d.error&&<p>{d.error}</p>}<button onClick={()=>onDocument(d)}>전체 내용 확인</button></div>)}<p className="text-sm">{env==='production'?'발행 버튼을 누르면 실제 세금계산서가 생성되고 거래처에 이메일이 전송됩니다.':'테스트 환경으로 요청합니다.'} 기존 발행 여부와 공급자·거래처·금액을 확인해 주세요.</p><label className="block my-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 표시된 문서 전체를 확인했고 중복 발행이 아닙니다.</label><button className="bg-slate-800 text-white rounded p-3" disabled={busy||!confirmed||!docs.some(d=>['draft','rejected'].includes(d.state))} onClick={()=>act(async()=>{
 const next=[...docs];for(let i=0;i<next.length;i++){if(!['draft','rejected'].includes(next[i].state))continue;try{next[i]=await post(`/drafts/${next[i].id}/issue`,{confirm:next[i].id,duplicateChecked:true});}catch(e:any){next[i]={...next[i],error:e.message};setMessage('일부 요청을 완료하지 못했습니다. 각 문서 상태를 확인해 주세요.');}setDocs([...next]);}setConfirmed(false);
 })}>{busy?'발행 요청 중…':'확인한 문서 일괄 발행'}</button><button className="ml-3" disabled={busy} onClick={()=>{setDocs([]);setGroups([]);}}>결과 닫기</button></div>}
 </section>;
}
