// Local-only visual preview. Fictional data; no storage.ts, production credentials, jobs or outbound services.
import express from 'express';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {registerSettlements} from '../server/settlement-review';
import {registerPurchaseLinks} from '../server/purchase-link';
import {digest} from '../server/settlement-files';
const db:any=new DatabaseSync(':memory:');
db.transaction=(fn:any)=>()=>{db.exec('BEGIN');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
db.exec(`CREATE TABLE suppliers(id INTEGER PRIMARY KEY,name TEXT);INSERT INTO suppliers VALUES(1,'클라리멘토');
CREATE TABLE customers(id INTEGER PRIMARY KEY,business_name TEXT,is_store INTEGER);INSERT INTO customers VALUES(1,'예시 카페',0);
CREATE TABLE product_categories(key TEXT,is_bean INTEGER);INSERT INTO product_categories VALUES('blend',1);
CREATE TABLE products(id INTEGER PRIMARY KEY,cost_price INTEGER);INSERT INTO products VALUES(1,22000),(2,30000);
CREATE TABLE orders(id INTEGER PRIMARY KEY,order_no TEXT,customer_id INTEGER,customer_snapshot TEXT,items TEXT,status TEXT,ecount_date TEXT,created_at INTEGER,auto_purchase_id INTEGER,is_store_order INTEGER);
CREATE TABLE purchases(id INTEGER PRIMARY KEY,supplier_id INTEGER,purchase_no TEXT UNIQUE,purchase_date TEXT,items TEXT,total_amount INTEGER,memo TEXT,segment TEXT,customer_id INTEGER,customer_name TEXT,created_at INTEGER);`);
const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.session={userId:1,role:'admin',adminRole:'owner'};next();});
registerSettlements(app,db,(_req,_res,next)=>next());registerPurchaseLinks(app,db,(_req,_res,next)=>next());
const pItem={productId:1,name:'코튼 블렌드 1kg',qty:3,unitPrice:22000,amount:66000};
db.prepare('INSERT INTO purchases VALUES(1,1,?,?,?,?,?,?,?,?,?)').run('PO-EXAMPLE-01','2026-09-17',JSON.stringify([pItem]),66000,'예시 발주','wholesale',1,'예시 카페',Date.now());
db.prepare('INSERT INTO orders VALUES(1,?,1,?,?,?, ?,?,1,0)').run('KC-EXAMPLE-01',JSON.stringify({businessName:'예시 카페'}),JSON.stringify([{...pItem,category:'blend',qty:4}]),'done','2026-09-17',Date.now());
const line=(source:string,qty:number,price?:number)=>({id:source+'-'+digest(source),source,date:'2026-09-17',customer:'예시 카페',product:'코튼',qty,unit:'1kg',reference:source==='chat'?'카톡 9월 17일 11:20':'원장!A2:D2',text:source==='chat'?'1. 예시 카페\n- 품목: 코튼 블렌드 1kg * 4':'2026-09-17 / 예시 카페 / 코튼 / 4',warnings:[],...(price?{unitPrice:price,amount:qty*price}:{})});
const excel={lines:[line('excel',4,21816)],issues:[],prices:{코튼:21816},supplyAmount:87264,vat:8726.4};
const chat={lines:[line('chat',4)],issues:[{date:'2026-09-17',reference:'카톡 9월 17일 14:29',text:'디카페인 1kg도 추가 부탁드립니다. (미리보기 예시)'}]};
db.prepare('INSERT INTO settlement_runs(month,supplier_id,fingerprint,excel_json,chat_json,created_at,created_by) VALUES(?,?,?,?,?,?,?)').run('2026-09',1,'preview',JSON.stringify(excel),JSON.stringify(chat),Date.now(),1);
app.get('/api/auth/me',(_req,res)=>res.json({id:1,role:'admin',adminRole:'owner',managerName:'미리보기',businessName:'니트커피'}));
app.get('/api/admin/suppliers',(_req,res)=>res.json([{id:1,name:'클라리멘토'}]));
app.use('/api',(_req,res)=>res.json([]));
const dir=resolve('dist/public');
app.get('/',(_req,res)=>res.type('html').send(readFileSync(resolve(dir,'index.html'),'utf8').replace('<body>','<body><div style="position:sticky;top:0;z-index:99999;background:#e9d5a4;color:#29271f;text-align:center;padding:8px;font:13px sans-serif">미리보기 · 모든 내역은 예시 데이터입니다 · 운영 장부와 연결되지 않습니다</div>')));
app.use(express.static(dir));
app.listen(8771,'127.0.0.1',()=>console.log('Preview: http://127.0.0.1:8771/?review=1#/admin/settlement-review'));
