import {useEffect,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useAuth} from '@/lib/auth';
import {apiRequest,queryClient} from '@/lib/queryClient';
import {errMsg} from '@/lib/format';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card} from '@/components/ui/card';
import type {PayrollContract,PayrollReport,PayrollDay,PayrollWeek} from '@shared/payroll';
const weekdays=['일','월','화','수','목','금','토'];
const money=(n:number)=>n.toLocaleString('ko-KR')+'원';
const hours=(m:number)=>`${Math.floor(m/60)}시간 ${Math.round((m%60)*100)/100}분`;
const today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
const selectClass='h-9 rounded-md border bg-background px-2 text-sm';
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}{children}</label>;}
export default function StaffPayroll(){
 const {user}=useAuth();const owner=user?.adminRole==='owner';
 const [month,setMonth]=useState(today().slice(0,7)),[staffId,setStaffId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const people=useQuery<{id:number;name:string;position:string;active:number}[]>({queryKey:['/api/admin/payroll'],enabled:owner});
 const key=`/api/admin/payroll/${staffId}?month=${month}`;
 const report=useQuery<PayrollReport>({queryKey:[key],enabled:owner&&!!staffId&&/^\d{4}-\d{2}$/.test(month),staleTime:0,refetchOnWindowFocus:true});
 async function save(path:string,body:unknown){setBusy(true);setError('');setMessage('');try{await apiRequest('POST',`/api/admin/payroll/${staffId}/${path}`,body);await queryClient.invalidateQueries({queryKey:[key]});setMessage('저장했어. 변경 이력도 함께 남겼어.');return true;}catch(e){setError(errMsg(e));return false;}finally{setBusy(false);}}
 if(!owner)return null;
 return <Card className="my-5 p-4 sm:p-5 space-y-4" aria-label="파트타이머 급여">
  <div><h2 className="font-semibold">파트타이머 급여</h2><p className="mt-1 text-xs text-muted-foreground">매월 1일~말일 · 계약시간 기준 · 출퇴근 원본은 그대로 보존합니다. 소유자만 열람·수정할 수 있습니다.</p></div>
  <div className="flex flex-wrap items-end gap-3"><Field label="급여 월"><Input aria-label="급여 월" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><Field label="급여 직원"><select aria-label="급여 직원" className={selectClass} value={staffId} onChange={e=>{setStaffId(e.target.value);setError('');setMessage('');}}><option value="">직원 선택</option>{people.data?.map(p=><option key={p.id} value={p.id}>{p.name}{p.active?'':' (비활성)'}</option>)}</select></Field><Button variant="outline" onClick={()=>report.refetch()} disabled={!staffId||busy}>새로고침</Button></div>
  {(error||report.error||people.error)&&<p role="alert" className="text-sm text-destructive">{error||errMsg(report.error||people.error)}</p>}{message&&<p role="status" className="text-sm">{message}</p>}
  {report.isLoading&&staffId&&<p>급여 계산 중…</p>}
  {report.data&&<PayrollDetail key={staffId+month} r={report.data} save={save} busy={busy}/>}
 </Card>;
}
function PayrollDetail({r,save,busy}:{r:PayrollReport;save:(path:string,data:unknown)=>Promise<boolean>;busy:boolean}){
 const [editContract,setEditContract]=useState<PayrollContract|null>(null),[newContract,setNewContract]=useState(false);
 const [day,setDay]=useState<PayrollDay|null>(null),[week,setWeek]=useState<PayrollWeek|null>(null);
 const editor=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(day||week)editor.current?.scrollIntoView({behavior:'smooth',block:'center'});},[day,week]);
 const [confirmed,setConfirmed]=useState(false),[reason,setReason]=useState('');
 function exportCsv(){
  const data=[['직원','급여 월','상태','기본급','주휴수당','일별 추가수당','월 추가액','공제액','세전 합계','공제 후 금액'],[r.name,r.month,r.confirmed?'확정':'검토 중',r.basePay,r.weeklyPay,r.supplements,r.additions,r.deductions,r.gross,r.net],[],['날짜','계약시간(분)','급여시간(분)','시급','기본급(원·반올림 전)','추가수당','확인 상태','사유'],...r.days.map(d=>[d.date,d.scheduledMinutes,d.paidMinutes,d.hourlyWage,d.amount,d.supplement,d.pending?'확인 필요':'확인됨',d.decision?.reason||'계약 기준']),[],['주휴일','주휴시간(분)','시급','주휴수당(원·반올림 전)','확인 상태','사유'],...r.weeks.map(w=>[w.date,w.minutes,w.hourlyWage,w.amount,w.pending?'확인 필요':'계산됨',w.reason||w.issues.join(' · ')])];
  const safe=(v:unknown)=>{const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';};
  const url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`급여-${r.staffId}-${r.month}.csv`;a.click();URL.revokeObjectURL(url);
 }
 return <>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['기본급',r.basePay],['주휴수당',r.weeklyPay],['세전 합계',r.gross],['공제 후 금액',r.net]].map(([label,n])=><div key={label} className="rounded border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold tabular-nums">{money(Number(n))}</p></div>)}</div>
  <p className="text-sm">{r.confirmed?'급여 확정됨':r.confirmedAt?'자료가 바뀌어 재확인이 필요합니다.':'예상 급여 · 아직 확정하지 않았습니다.'} · 확인 필요 {r.pending}건</p>
  {r.warnings.map(w=><p key={w} className="text-sm text-amber-800">{w}</p>)}
  <details open={!r.contracts.length} className="rounded border p-3"><summary className="cursor-pointer font-medium text-sm">계약 근무시간·시급 ({r.contracts.length})</summary><div className="mt-3 space-y-3">
   {r.contracts.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm"><div>{c.from} ~ {c.to||'종료 미정'} · {money(c.hourlyWage)}<p className="text-xs text-muted-foreground">{c.days.map(d=>`${weekdays[d.weekday]} ${d.start}~${d.end}`).join(' / ')} · 주휴 {weekdays[c.holidayWeekday]}요일</p></div><Button variant="outline" size="sm" disabled={busy} onClick={()=>{setEditContract(c);setNewContract(false);}}>계약 수정</Button></div>)}
   <Button variant="outline" disabled={busy} onClick={()=>{setEditContract(null);setNewContract(true);}}>계약 추가</Button>
   <p className="text-xs text-muted-foreground">시급·근무시간 변경은 이전 계약의 종료일을 정하고 새 계약을 추가해 주세요. 지난 급여에 영향을 주는 수정은 다시 확인하도록 표시됩니다. 근무표는 자동 변경하지 않습니다.</p>
   {(newContract||editContract)&&<ContractEditor key={editContract?.id||'new'} initial={editContract} staffId={r.staffId} save={save} busy={busy} close={()=>{setNewContract(false);setEditContract(null);}}/>}
  </div></details>
  <details open={r.pending>0} className="rounded border p-3"><summary className="cursor-pointer text-sm font-medium">일별 급여 · 계약과 출퇴근 비교</summary><div className="mt-3 divide-y">{r.days.map(d=><div key={d.date} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><div><b>{d.date} ({weekdays[new Date(d.date+'T00:00:00Z').getUTCDay()]})</b><p>계약 {hours(d.scheduledMinutes)} → 급여 {hours(d.paidMinutes)} · {money(Math.ceil(d.amount+d.supplement))}</p><p className="text-xs text-muted-foreground">출퇴근 {d.clockIn||'미기록'} ~ {d.clockOut||'미기록'}{d.actualMinutes!==null?` · 기록상 ${hours(d.actualMinutes)}`:''}</p>{d.issues.length>0&&<p className={d.pending?'text-xs text-amber-800':'text-xs text-muted-foreground'}>{d.pending?'확인 필요: ':'확인됨: '}{d.issues.join(' · ')}</p>}{d.decision&&<p className="text-xs text-muted-foreground">{d.decision.reason}</p>}</div><Button size="sm" variant="outline" disabled={busy} onClick={()=>{setDay(d);setWeek(null);}}>확인·조정</Button></div>)}</div></details>
  <details className="rounded border p-3" open={r.weeks.some(w=>w.pending)}><summary className="cursor-pointer text-sm font-medium">주휴수당 · {money(r.weeklyPay)}</summary><p className="my-2 text-xs text-muted-foreground">주휴일이 속한 달에 한 번 계산합니다. 4주 평균 주 소정근로 15시간 이상·소정근로일 개근을 기준으로 하며 지각·조퇴 자체는 결근이 아닙니다. 입·퇴사, 계약 변경, 휴가 등 예외는 소유자가 확인합니다.</p>{r.weeks.map(w=><div key={w.date} className="flex flex-wrap items-center justify-between gap-2 border-t py-3 text-sm"><div><b>{w.date} 주휴일</b><p>{w.from}~{w.date} · {hours(w.minutes)} · {money(Math.ceil(w.amount))}</p><p className="text-xs text-muted-foreground">직전 4주 평균 주 {hours(w.scheduledAverage)}{w.reason?' · '+w.reason:''}</p>{w.issues.length>0&&<p className="text-xs text-amber-800">{w.pending?'확인 필요: ':'확인됨: '}{w.issues.join(' · ')}</p>}</div><Button size="sm" variant="outline" disabled={busy} onClick={()=>{setWeek(w);setDay(null);}}>주휴 조정</Button></div>)}</details>
  <div ref={editor} className="space-y-3">{day&&<DayEditor key={day.date+day.fingerprint} day={day} busy={busy} save={save} close={()=>setDay(null)}/>}
  {week&&<WeekEditor key={week.date+week.fingerprint} week={week} busy={busy} save={save} close={()=>setWeek(null)}/>}</div>
  <details className="rounded border p-3"><summary className="cursor-pointer font-medium text-sm">추가 지급·공제</summary><MonthEditor key={r.fingerprint+r.monthReason} r={r} save={save} busy={busy}/></details>
  <details className="text-xs text-muted-foreground"><summary className="cursor-pointer">계산 기준과 확인할 내용</summary><div className="mt-2 space-y-2"><p>기본급 = 소유자가 인정한 급여시간 × 해당 날짜 계약 시급. 5인 이상으로 설정한 경우 계약시간 초과분에 50% 가산분을 자동 더합니다. 야간·휴일근로와 유급 공휴일, 기타 수당은 확인 후 일별 추가수당 또는 월 추가 지급에 입력해 주세요.</p><p>기본급·주휴수당은 월 합산 후 각각 원 미만을 올립니다. 주휴시간 = 직전 4주 총 소정근로시간 ÷ 통상근로자의 4주 소정근로일수. 규칙적인 계약이 유지된 경우 자동 계산합니다. 근무형태가 불규칙하거나 비교할 통상근로자가 없는 경우 산정 기준을 확인해 조정해 주세요.</p><p>세금·4대보험·퇴직금은 자동 계산하지 않습니다. 확정된 공제액을 입력하면 공제 후 금액에 반영됩니다. 이 화면은 송금하거나 출퇴근·근무표 원본을 수정하지 않습니다.</p></div></details>
  <div className="border-t pt-3 space-y-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>추가근무·야간·휴일·유급휴일 수당과 공제액을 확인했습니다.</label><Input aria-label="급여 확정 사유" placeholder="급여 확정 사유 / 확인 메모" value={reason} onChange={e=>setReason(e.target.value)}/><div className="flex flex-wrap gap-2"><Button disabled={busy||!confirmed||!reason.trim()||!!r.pending} onClick={async()=>{if(await save('confirm',{month:r.month,fingerprint:r.fingerprint,confirmationKey:r.confirmationKey,reason,reviewed:confirmed})){setConfirmed(false);setReason('');}}}>월 급여 확정</Button><Button variant="outline" onClick={exportCsv}>급여 내역 내려받기</Button></div><p className="text-xs text-muted-foreground">확정은 월말이 지난 뒤 가능합니다. 이후 계약·근태·금액이 바뀌면 재확인 상태로 표시됩니다.</p></div>
  <details className="text-xs"><summary className="cursor-pointer">수정 이력 ({r.history.length})</summary>{r.history.map((h,i)=><p className="mt-2" key={i}>{new Date(h.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · {h.key} · {h.reason} · 소유자 #{h.actor}</p>)}</details>
 </>;
}
function ContractEditor({initial,staffId,save,busy,close}: {initial:PayrollContract|null;staffId:number;save:(p:string,b:unknown)=>Promise<boolean>;busy:boolean;close:()=>void}){
 const [c,setC]=useState<PayrollContract>(initial||{staffId,from:today(),to:null,hourlyWage:10320,days:[1,2,3,4,5].map(weekday=>({weekday,start:'11:30',end:'14:30',breakMinutes:0})),holidayWeekday:0,normalDaysPerWeek:5,workplaceSize:'unknown',reason:''});
 const field=(k:string,v:any)=>setC(p=>({...p,[k]:v}));
 return <fieldset disabled={busy} className="rounded bg-muted/40 p-3 space-y-3"><p className="text-sm font-medium">{initial?'계약 수정':'계약 추가 · 실제 계약서를 기준으로 입력'}</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Field label="적용 시작일"><Input type="date" value={c.from} onChange={e=>field('from',e.target.value)}/></Field><Field label="계약 종료일 (선택)"><Input type="date" value={c.to||''} onChange={e=>field('to',e.target.value||null)}/></Field><Field label="시급 (주휴 별도)"><Input type="number" min="1" value={c.hourlyWage} onChange={e=>field('hourlyWage',Number(e.target.value))}/></Field><Field label="주휴 요일"><select className={selectClass} value={c.holidayWeekday} onChange={e=>field('holidayWeekday',Number(e.target.value))}>{weekdays.map((d,i)=><option key={d} value={i}>{d}요일</option>)}</select></Field><Field label="동종 통상근로자 주 소정근로일수"><Input type="number" min="1" max="6" value={c.normalDaysPerWeek} onChange={e=>field('normalDaysPerWeek',Number(e.target.value))}/></Field><Field label="사업장 적용 기준"><select className={selectClass} value={c.workplaceSize} onChange={e=>field('workplaceSize',e.target.value)}><option value="unknown">확인 필요</option><option value="under5">상시 5인 미만</option><option value="5plus">상시 5인 이상</option></select></Field></div>
 <p className="text-xs text-muted-foreground">요일별 계약 출근·퇴근·무급 휴게시간입니다. 야간·날짜 넘김 계약은 이 설정에서 자동 계산하지 않습니다.</p>
 {weekdays.map((w,i)=>{const d=c.days.find(d=>d.weekday===i);const update=(k:string,v:any)=>field('days',c.days.map(x=>x.weekday===i?{...x,[k]:v}:x));return <div key={w} className="flex flex-wrap items-center gap-2 text-sm"><label className="w-16"><input type="checkbox" checked={!!d} onChange={e=>field('days',e.target.checked?[...c.days,{weekday:i,start:'11:30',end:'14:30',breakMinutes:0}].sort((a,b)=>a.weekday-b.weekday):c.days.filter(x=>x.weekday!==i))}/> {w}</label>{d&&<><Input aria-label={`${w} 출근`} className="w-28" type="time" value={d.start} onChange={e=>update('start',e.target.value)}/><span>~</span><Input aria-label={`${w} 퇴근`} className="w-28" type="time" value={d.end} onChange={e=>update('end',e.target.value)}/><Input aria-label={`${w} 휴게 분`} className="w-20" type="number" min="0" value={d.breakMinutes} onChange={e=>update('breakMinutes',Number(e.target.value))}/><span className="text-xs">분 무급 휴게</span></>}</div>;})}
 <Input aria-label="계약 변경 사유" value={c.reason} onChange={e=>field('reason',e.target.value)} placeholder="등록·변경 사유 (필수)"/><div className="flex gap-2"><Button onClick={async()=>{if(await save('contracts',c))close();}}>계약 저장</Button><Button variant="ghost" onClick={close}>닫기</Button></div></fieldset>;
}
function DayEditor({day:d,save,busy,close}:{day:PayrollDay;save:(p:string,b:unknown)=>Promise<boolean>;busy:boolean;close:()=>void}){
 const [minutes,setMinutes]=useState(d.paidMinutes),[attendance,setAttendance]=useState(d.decision?.attendance||'present'),[supplement,setSupplement]=useState(d.decision?.supplement||0),[reason,setReason]=useState('');
 return <fieldset disabled={busy} className="rounded border-2 p-4 space-y-3"><b>{d.date} 급여 확인</b><p className="text-xs">기본값은 계약 {hours(d.scheduledMinutes)}입니다. 실제 추가근무를 했다면 급여시간에 포함해 주세요. 지각·조퇴는 ‘출근’으로 두고 급여시간만 조정합니다.</p><div className="grid grid-cols-2 gap-3"><Field label="급여 인정 시간 (분)"><Input type="number" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field><Field label="주휴 개근 판단"><select className={selectClass} value={attendance} onChange={e=>setAttendance(e.target.value as any)}><option value="present">출근 (지각·조퇴 포함)</option><option value="absent">결근</option><option value="paidLeave">유급휴가</option><option value="excluded">소정근로일 제외 · 주휴 별도 검토</option></select></Field><Field label="기타 추가수당 (원)"><Input type="number" min="0" value={supplement} onChange={e=>setSupplement(Number(e.target.value))}/></Field></div><p className="text-xs text-muted-foreground">5인 이상이면 계약시간 초과분의 50% 가산이 별도 자동 계산됩니다. 여기에는 중복 없이 야간·휴일 등 나머지 수당을 입력하세요.</p><Input aria-label="일별 급여 조정 사유" value={reason} onChange={e=>setReason(e.target.value)} placeholder="예: 조기 출근·늦은 퇴근은 개인 체류, 실제 근무 3시간"/><div className="flex gap-2"><Button disabled={!reason.trim()} onClick={async()=>{if(await save('day',{date:d.date,paidMinutes:minutes,attendance,supplement,reason,fingerprint:d.fingerprint}))close();}}>확인 저장</Button><Button variant="ghost" onClick={close}>닫기</Button></div></fieldset>;
}
function WeekEditor({week:w,save,busy,close}:{week:PayrollWeek;save:(p:string,b:unknown)=>Promise<boolean>;busy:boolean;close:()=>void}){
 const [minutes,setMinutes]=useState(w.minutes),[reason,setReason]=useState('');return <fieldset disabled={busy} className="rounded border-2 p-4 space-y-3"><b>{w.date} 주휴 확인</b><p className="text-xs">계약과 개근 요건을 확인한 주휴시간을 입력하세요. 미지급이면 0분과 사유를 입력합니다. 입사 초기·계약 변경·주 전체 휴가·퇴사 주는 별도 확인이 필요합니다.</p><Field label="주휴 유급시간 (분)"><Input type="number" step="0.01" min="0" max="480" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field><Input aria-label="주휴 조정 사유" placeholder="주휴 산정·조정 사유 (필수)" value={reason} onChange={e=>setReason(e.target.value)}/><div className="flex gap-2"><Button disabled={!reason.trim()} onClick={async()=>{if(await save('week',{date:w.date,minutes,reason,fingerprint:w.fingerprint}))close();}}>주휴 저장</Button><Button variant="ghost" onClick={close}>닫기</Button></div></fieldset>;
}
function MonthEditor({r,save,busy}:{r:PayrollReport;save:(p:string,b:unknown)=>Promise<boolean>;busy:boolean}){
 const [additions,setAdditions]=useState(r.additions),[deductions,setDeductions]=useState(r.deductions),[reason,setReason]=useState(r.monthReason);return <fieldset disabled={busy} className="mt-3 space-y-3"><div className="grid grid-cols-2 gap-3"><Field label="월 추가 지급액 (원)"><Input type="number" min="0" value={additions} onChange={e=>setAdditions(Number(e.target.value))}/></Field><Field label="확인된 세금·보험 등 공제액 (원)"><Input type="number" min="0" value={deductions} onChange={e=>setDeductions(Number(e.target.value))}/></Field></div><Input aria-label="추가 지급 공제 사유" placeholder="항목별 금액과 근거를 적어주세요." value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!reason.trim()} onClick={()=>save('month',{month:r.month,additions,deductions,reason,fingerprint:r.fingerprint})}>추가·공제 저장</Button></fieldset>;
}
